apiVersion: "extensions/v1beta1"
kind: Ingress
metadata:
  name: hello
spec:
  rules:
    - http:
        paths:
          - path: "/api/hello"
            backend:
              serviceName: hello
              servicePort: 10000
          - path: "/direct-stream"
            backend:
              serviceName: "hello-stream"
              servicePort: 10000
          - path: "/auto-stream"
            backend:
              serviceName: "hello-stream"
              servicePort: 10000